### PR TITLE
Rearrange a bit and make it abi3 compatible.

### PR DESCRIPTION
**Pull request by Sachaa-Thanasius**
This way, the package doesn't need to be recompiled for any future minor releases.

However, this particular pull request changes a *lot* related to package config/setup, which I know shouldn't be done since it's personal preference. Didn't go through the effort of separating that back out yet, but it can be fixed if it means the PR will be considered.

### CODE REVIEW

**Comment by Sachaa-Thanasius** [comment]
Assuming this functionality were added, it might be prudent for the README to have a warning and an example for making sure this is only installed on python 3.13+

For example, borrowing language from a [similar third-party backport](https://pypi.org/project/nntplib/#description) for a PEP 594 dead battery:
>Because `audioop` is still a valid library in all relevant versions of the standard library up to and including Python 3.12, care should be taken to avoid a conflict when installing and importing it. For example, use this line in your `install_requires`, `project.dependencies` section, requirements.txt file, etc.:
> 
> ```
> 'audioop; python_version>="3.13"'
> ```

**Comment by AbstractUmbra** [comment]
> Assuming this functionality were added, it might be prudent for the README to have a warning and an example for making sure this is only installed on python 3.13+.
> 
> For example, borrowing language from a [similar third-party backport](https://pypi.org/project/nntplib/#description) for a PEP 594 dead battery:
> 
> > Because `audioop` is still a valid library in all relevant versions of the standard library up to and including Python 3.12, care should be taken to avoid a conflict when installing and importing it. For example, use this line in your `install_requires`, `project.dependencies` section, requirements.txt file, etc.:
> > ```
> > 'audioop; python_version>="3.13"'
> > ```
> 
> Maybe after 3.13 is released officially, the project metadata would then be updated to put the lower bound at 3.13, avoiding the possible footgun.
> 
> Not sure if including that is within the scope of this PR, but it's still maybe something worthy of consideration.

This was an oversight by me, feel free to edit the relevant library meta to only allow 3.13+ as well as the README with the changes presented here.

**Comment by Sachaa-Thanasius** [comment]
Oh, coolio. I'll get on that.

**Comment by AbstractUmbra** [comment]
> Oh, coolio. I'll get on that.

Further note, sorry, if the library meta only allows installation on 3.13+ the warning in the readme is not relevant, aha.

**Comment by Sachaa-Thanasius** [comment]
Aight, fixed. On a related note, the idea came to mind to add a link to PEP 594 and/or the stdlib audioop docs (or even copying the docs .rst file in), but that isn't really in scope for this PR either. Figured I'd still bring it up.

**Comment by AbstractUmbra** [comment]
I've caused a merge conflict by updating `main` with the current metadata needs, you'll need to rebase and resolve the merge I think, sorry about that!

**Comment by Sachaa-Thanasius** [comment]
Let's see if I broke it.

**Comment by Sachaa-Thanasius** [comment]
Yeah, this is ugly as sin, even if it worked. Sorry about that; my git knowledge isn't the best. @AbstractUmbra

**Comment by Sachaa-Thanasius** [comment]
Anything else that needs to be considered or is on a wishlist for this?

**Comment by AbstractUmbra** [comment]
> Anything else that needs to be considered or is on a wishlist for this?

Looks all good, thanks!

**Pull request merged**
